---
title: "MOM6 surface Temperature"
author: "Brandon Beltz"
date: "`r Sys.Date()`"
output:
  html_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ecodata)
library(ecodata25)
library(dplyr)
library(knitr)
library(ggplot2)
```

# MOM6 surface {.tabset}

## MAB Forecast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("forecast",Var)) |>
  dplyr::filter(EPU == "MAB")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```

## GB Forecast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("forecast",Var)) |>
  dplyr::filter(EPU == "GB")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```

## GOM Forecast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("forecast",Var)) |>
  dplyr::filter(EPU == "GOM")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```

## MAB hindcast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("hindcast",Var)) |>
  dplyr::filter(EPU == "MAB")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```

## GB hindcast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("hindcast",Var)) |>
  dplyr::filter(EPU == "GB")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```

## GOM hindcast 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fix <- ecodata::surface_temp_mom6 |>
  dplyr::filter(grepl("hindcast",Var)) |>
  dplyr::filter(EPU == "GOM")

p <- fix |>
  ggplot2::ggplot(ggplot2::aes(x = Time, y = Value, color=Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Temperature (C)")

p
```
