name: Bug Report
description: Identify a problem or unexpected outcome
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Please explain the problem you are experiencing
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our product are you using?
      placeholder: X.X.X
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      options:
        - Windows
        - Mac
        - Linux
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System information
      description: Please provide the following system information
      value: |
        - R version: 
        - IDE: 
        - IDE version: 
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Please explain the steps required to reproduce the problem. Ideally, include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: What is the observed outcome of following the steps above?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What outcome did you expect from following the steps above?
    validations:
      required: true
  - type: input
    id: bug-impact
    attributes:
      label: Bug impact
      description: How severely does this problem impact you and/or your work?
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, you may upload screenshots to demonstrate the problem.
    validations:
      required: false
