---
title: "Trend Lines: Revisited"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ecodata)
library(tidyverse)
library(stringr)
library(plotly)

council <- "Mid-Atlantic Fishery Management Council"
council_abbr <- "MAFMC"
#Region identifiers
epu <- "Mid-Atlantic Bight"
epu_abbr <- "MAB"
region <- "Mid-Atlantic"
region_abbr <- "MA" #Some commercial data organized by "MA" or "NE" regions, not by EPU 

#Time series constants
shade.alpha <- 0.3
shade.fill <- "lightgrey"
lwd <- 1
pcex <- 2
trend.alpha <- 0.5
trend.size <- 2
hline.size <- 1
hline.alpha <- 0.35
hline.lty <- "dashed"
label.size <- 5
hjust.label <- 1.5
letter_size <- 4
feeding.guilds1<- c("Piscivore","Planktivore","Benthivore","Benthos")
feeding.guilds <- c("Apex Predator","Piscivore","Planktivore","Benthivore","Benthos")
x.shade.min <- 2010
x.shade.max <- 2020
#Define constants for figure plot
series.col <- c("indianred","black")

label <- function(variable,value){
  return(facet_names[value])
}
```

Landings - Mid-Atlantic Bight
=======================================================================

Row {data-height=200}
-----------------------------------------------------------------------

### Background

Landings from Mid-Atlantic Managed spp. SOE reports decreasing through time. 
Questions:
 * What are we trying to answer?
 
```{r, setup2}
managed_landings <- ecodata::comdat  %>%
  dplyr::filter(stringr::str_detect(Var, paste0(council_abbr," managed species - Landings weight|JOINT managed species - Landings weight")),
         !stringr::str_detect(Var, "Other"),
         Time >= 1986,
         EPU == epu_abbr)
# HMS Landings
apex<-ecodata::hms_landings %>% 
  dplyr::filter(stringr::str_detect(Var, "Landings")) %>% 
  separate(Var, c("Var", "trash"), sep = "_") %>% 
  group_by(Time) %>% 
  summarise(Value = sum(Value)) %>% 

  mutate(Var = c("HMS Landings"), 
         Units = c("metric tons"), 
         EPU = c("MAB"))
#Total landings
total_landings <- ecodata::comdat  %>%
  dplyr::filter(!stringr::str_detect(Var, "managed species"),
         !stringr::str_detect(Var, "Other"),
         !stringr::str_detect(Var, "Apex"),
         stringr::str_detect(Var, "Landings"),
         Time >= 1986,
         EPU == epu_abbr) %>% 
  rbind(apex)
total_landings_agg <- total_landings %>%
  dplyr::group_by(Time) %>%
  dplyr::summarise(Value = sum(Value)) %>% 
  dplyr::mutate(Var = "Total",hline = mean(Value))
managed_landings_agg <- managed_landings %>%
  dplyr::group_by(Time) %>%
  dplyr::summarise(Value = sum(Value)) %>% 
  dplyr::mutate(Var = "Managed",hline = mean(Value))

landings_agg <- rbind(total_landings_agg, managed_landings_agg)
```

Row {data-height=800}
-----------------------------------------------------------------------

```{r}
#Managed landings


p2<- ggplot(data = landings_agg)+
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  #ecodata::geom_gls(aes(x = Time, y = Value,
  #             group = Var),
  #           alpha = trend.alpha, size = trend.size) +
  ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value, color = Var), size = pcex) +
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  #ggplot2::ylab(expression("Landings (10"^3*"mt)")) +
  #ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline,
               color = Var),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::ggtitle("Total Landings")+
  ggplot2::theme(axis.title.y = element_text(size = 7))+
  ecodata::theme_ts()+
  ecodata::theme_title()
#plotly::ggplotly(p2)

```


### SOE 2021 

```{r, fig.height=3, fig.width=6}
p3<- ggplot2::ggplot(data = landings_agg)+
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls(aes(x = Time, y = Value,
               group = Var),
             alpha = trend.alpha, size = trend.size) +
  ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value, color = Var), size = pcex) +
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::ylab(expression("Landings (10"^3*"mt)")) +
  ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline,
               color = Var),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::ggtitle("Total Landings")+
  ggplot2::theme(axis.title.y = element_text(size = 7))+
  ecodata::theme_ts()+
  ecodata::theme_title()
#plotly::ggplotly(p3)
p3

```

### Managed Only

```{r, fig.height=3, fig.width=6}

land <- landings_agg %>% 
  filter(Var == "Managed")


p3<- ggplot(data = land)+
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls(aes(x = Time, y = Value,
               group = Var),
             alpha = trend.alpha, size = trend.size) +
  ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value, color = Var), size = pcex) +
  #ggplot2::geom_line(aes(x =Time, y = test$fitted.values))+
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::ylab(expression("Landings (10"^3*"mt)")) +
  ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline,
               color = Var),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::ggtitle("Managed Landings")+
  ggplot2::theme(axis.title.y = element_text(size = 7))+
  ecodata::theme_ts()+
  ecodata::theme_title()
#plotly::ggplotly(p3)
p3 
```

Column {data-width=350}
-----------------------------------------------------------------------
### Stats

```{r}

data <- landings_agg %>% 
  filter(Var == "Managed") %>% 
  select(Time, Value) %>% 
  rename(x = Time, y = Value)


constant_norm <- nlme::gls(y ~ 1, 
                           data = data, na.action = na.omit)
constant_ar1 <- nlme::gls(y ~ 1, data = data, 
                          correlation = nlme::corAR1(form = ~x),
                           na.action = na.omit)

                     
                     
# Linear model with normal error
linear_norm <- nlme::gls(y ~ x, data = data, na.action = na.omit)
# Linear model with AR1 error
linear_ar1 <- nlme::gls(y ~ x, data = data,
                        correlation = nlme::corAR1(form = ~x),
                        na.action = na.omit)

# Polynomial model with normal error
data$x2 <- data$x^2
poly_norm <- nlme::gls(y ~ x + x2, data = data, na.action = na.omit)
                     
# Polynomial model with AR1 error
poly_ar1 <-nlme::gls(y ~ x + x2,data = data,
                     correlation = nlme::corAR1(form = ~x),
                     na.action = na.omit)
                     

df_aicc <-data.frame(model = c("poly_norm","poly_ar1",
                               "linear_norm","linear_ar1"),
                     aicc  =
                       c(AICcmodavg::AICc(poly_norm),
                         AICcmodavg::AICc(poly_ar1),
                         AICcmodavg::AICc(linear_norm),
                         AICcmodavg::AICc(linear_ar1)),
                     coefs = rbind(coef(poly_norm),
                                   coef(poly_ar1),
                                   c(coef(linear_norm), NA),
                                   c(coef(linear_ar1),  NA)),
                     # Calculate overall signifiance (need to use
                     # ML not REML for this)
                     pval = c(anova(update(constant_norm, method = "ML"),
                                    update(poly_norm, method = "ML"))$`p-value`[2],
                              anova(update(constant_ar1, method = "ML"),
                                    update(poly_ar1, method = "ML"))$`p-value`[2],
                              anova(update(constant_norm, method = "ML"),
                                    update(linear_norm, method ="ML"))$`p-value`[2],
                              anova(update(constant_ar1, method = "ML"),
                                    update(linear_ar1, method = "ML"))$`p-value`[2]))

df_aicc

```


Landing - GAMs - MAB
=======================================================================

Row 
-----------------------------------------------------------------------

### GAM

```{r, fig.height=3, fig.width=6}
land <- landings_agg %>% 
  filter(Var == "Managed")

gam_mod <- mgcv::gam(Value ~ s(Time), data = land)
pred<- predict(gam_mod, se = "TRUE")

gam_df<- data.frame(fitted = gam_mod$fitted.values, 
                    pred = pred$fit,
                    se = pred$se.fit,
                    Time = c(1986:2021))
all<- land %>% left_join(gam_df) %>% 
  mutate(upper = (fitted + se), 
         lower = (fitted - se))


ggplot(data = all)+
  
  #Highlight last ten years
  # ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
  #     xmin = x.shade.min , xmax = x.shade.max,
  #     ymin = -Inf, ymax = Inf) +
  #ecodata::geom_gls(aes(x = Time, y = Value,
  #             group = Var),
  #           alpha = trend.alpha, size = trend.size) +
  #ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value), size = pcex) +
  ggplot2::geom_line(aes(x =Time, y = fitted))+
  ggplot2::geom_ribbon(aes(ymin = lower, ymax = upper, x = Time), alpha = 0.2)+
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::ylab(expression("Landings (10"^3*"mt)")) +
  ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::ggtitle("Managed Landings - GAM")+
  ggplot2::theme(axis.title.y = element_text(size = 7))+
  ecodata::theme_ts()+
  ecodata::theme_title()

```

### Stats

```{r}
summary(gam_mod)
```

Column 
-----------------------------------------------------------------------
### Local Trends
```{r}

```

### Thresholds
```{r}

```

Revenue - Mid-Atlantic Bight
=======================================================================

Row {data-height=200}
-----------------------------------------------------------------------

### Background 

Revenue from Mid-Atlantic managed spp. 

```{r, setup3}
## Apex pred
apex<-ecodata::hms_landings %>% 
  dplyr::filter(stringr::str_detect(Var, "Revenue")) %>% 
  separate(Var, c("Var", "trash"), sep = "_") %>% 
  group_by(Time) %>% 
  summarise(Value = sum(Value)) %>% 
  mutate(Var = c("HMS Revenue"), 
         Units = c("metric tons"), 
         EPU = c("MAB"))
#Filtering and aggregation step
rev_agg <- ecodata::comdat %>% 
  dplyr::filter(stringr::str_detect(Var, "Revenue"),
         !stringr::str_detect(Var, "Apex|prop|Other|NEFMC"), #Remove proportions, "Other" category species, NEFMC managed species in MAB
         EPU == epu_abbr,
         Time >= 1986) %>% 
  rbind(apex) %>% 
  dplyr::mutate(Status = ifelse(str_detect(Var, "managed"), 
                         "Managed","Total")) %>% #Create groups for aggregation
  dplyr::group_by(Status, Time) %>% 
  dplyr::summarise(Total = sum(Value)) %>% 
  dplyr::group_by(Status) %>% 
  dplyr::mutate(hline = mean(Total))

series.col <- c("indianred","black")
```

Row {data-height=800}
-----------------------------------------------------------------------

### SOE 2021 

```{r, fig.height=3, fig.width=6}

#Plotting
ggplot2::ggplot(data = rev_agg) +
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf)+  
  
  #lines
  ecodata::geom_gls(aes(x = Time, y = Total,
               group = Status),
             alpha = trend.alpha, size = trend.size) +
  ggplot2::geom_line(aes(x = Time, y = Total, color = Status), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Total, color = Status), size = 1.5) +

  #axes
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
      scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::ggtitle("Total revenue") +
  ggplot2::ylab(expression("Revenue (10"^6*"USD)")) +
  ggplot2::geom_hline(aes(yintercept = hline,
               color = Status),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::xlab(element_blank())+
  ecodata::theme_ts()+
  ecodata::theme_title()

```



### Managed Only

```{r, fig.height=3, fig.width=6}

rev<- rev_agg %>%   rename(Var = Status, 
                           Value = Total) %>% 
  filter(Var == "Managed")

p3<- ggplot(data = rev)+
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls(aes(x = Time, y = Value,
               group = Var),
             alpha = trend.alpha, size = trend.size) +
  ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value, color = Var), size = pcex) +
  #ggplot2::geom_line(aes(x =Time, y = test$fitted.values))+
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2015, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::ylab(expression("Landings (10"^3*"mt)")) +
  ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline,
               color = Var),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ggplot2::ggtitle("Total Landings")+
  ggplot2::theme(axis.title.y = element_text(size = 7))+
  ecodata::theme_ts()+
  ecodata::theme_title()
#plotly::ggplotly(p3)
p3 
```




Column {data-width=350}
-----------------------------------------------------------------------

### Stats

```{r}

data <- rev %>% 
  select(Time, Value) %>% 
  rename(x = Time, y = Value)


constant_norm <- nlme::gls(y ~ 1, 
                           data = data, na.action = na.omit)
constant_ar1 <- nlme::gls(y ~ 1, data = data, 
                          correlation = nlme::corAR1(form = ~x),
                           na.action = na.omit)

                     
                     
# Linear model with normal error
linear_norm <- nlme::gls(y ~ x, data = data, na.action = na.omit)
# Linear model with AR1 error
linear_ar1 <- nlme::gls(y ~ x, data = data,
                        correlation = nlme::corAR1(form = ~x),
                        na.action = na.omit)

# Polynomial model with normal error
data$x2 <- data$x^2
poly_norm <- nlme::gls(y ~ x + x2, data = data, na.action = na.omit)
                     
# Polynomial model with AR1 error
poly_ar1 <-nlme::gls(y ~ x + x2,data = data,
                     correlation = nlme::corAR1(form = ~x),
                     na.action = na.omit)
                     

df_aicc <-data.frame(model = c("poly_norm","poly_ar1",
                               "linear_norm","linear_ar1"),
                     aicc  =
                       c(AICcmodavg::AICc(poly_norm),
                         AICcmodavg::AICc(poly_ar1),
                         AICcmodavg::AICc(linear_norm),
                         AICcmodavg::AICc(linear_ar1)),
                     coefs = rbind(coef(poly_norm),
                                   coef(poly_ar1),
                                   c(coef(linear_norm), NA),
                                   c(coef(linear_ar1),  NA)),
                     # Calculate overall signifiance (need to use
                     # ML not REML for this)
                     pval = c(anova(update(constant_norm, method = "ML"),
                                    update(poly_norm, method = "ML"))$`p-value`[2],
                              anova(update(constant_ar1, method = "ML"),
                                    update(poly_ar1, method = "ML"))$`p-value`[2],
                              anova(update(constant_norm, method = "ML"),
                                    update(linear_norm, method ="ML"))$`p-value`[2],
                              anova(update(constant_ar1, method = "ML"),
                                    update(linear_ar1, method = "ML"))$`p-value`[2]))

df_aicc

```
