---
title: "get_dataset_attributes"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(
  devtools, dplyr, here, knitr, purrr, tidyr)
load_all(here())

ds_ls <- data(package = "ecodata") %>% .$results %>% .[,3]
not_null <- function(x) !is.null(x)
datasets <- tibble(
  name = ds_ls) %>% 
  mutate(
    data = map(name, function(name){
      d <- try(get(name), silent = T)
      if ("try-error" %in% class(d))
        return(NA)
      d}),
    data_steward = map(data, function(data){
      attr(data, "data_steward")}),
    tech_doc_url = map(data, function(data){
      attr(data, "tech-doc_url")}),
    data_files = map(data, function(data){
      attr(data, "data_files") %>% 
        unlist()}),
    has_data = map_lgl(data, function(data){
      if (length(data) == 1 && is.na(data[[1]]))
        return(F)
      T}),
    has_steward = map_lgl(data_steward, not_null),
    has_doc     = map_lgl(tech_doc_url, not_null),
    has_files   = map_lgl(data_files  , not_null))

datasets_todo <- datasets %>% 
  select(name, starts_with("has")) %>% 
  rowwise() %>% 
  mutate(
    has_missing = any(!has_data, !has_steward, !has_doc, !has_files)) %>% 
  filter(has_missing) %>% 
  select(-has_missing)

datasets_done <- datasets %>% 
  anti_join(datasets_todo, by = "name") %>% 
  select(name, starts_with("has"))

dataset_stewards <- datasets %>% 
  select(name, data_steward) %>% 
  unnest(data_steward)

dataset_techdocurls <- datasets %>% 
  select(name, tech_doc_url) %>% 
  unnest(tech_doc_url)

dataset_datafiles <- datasets %>% 
  select(name, data_files) %>% 
  unnest(data_files)
```

## datasets

### done

```{r}
kable(datasets_done)
```

### todo

```{r}
kable(datasets_todo)
```

## attributes

### stewards

```{r}
kable(dataset_stewards)
```

### docs

```{r}
kable(dataset_techdocurls)
```

### files

```{r}
kable(dataset_datafiles)
```
