---
title: "State of the Ecosystem 2018-2019"
subtitle: "Mid-Atlantic Bight"
author: "Ecosystems Dynamics and Assessment Branch"
date: "`r Sys.Date()`"
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
library(dplyr)
library(ggplot2)
library(lubridate)
library(here)
library(tidyr)
library(stringr)
library(zoo)

# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE,
                      cache.extra = packageVersion('tufte'),
                      cache = TRUE)
options(htmltools.dir.version = FALSE)


clean.dir <- here("data") #output directory for cleaned data
```

# Introduction

# Mid-Atlantic Bight Storminess

```{r fig-main, fig.cap = "Averaged total wind speed in the Mid-Atlantic Bight by season.", fig.align = 'center', echo = F,fig.height=4}
load(file.path(clean.dir, "wind_clean.Rdata"))

wind_clean %>%
  filter(str_detect(Var, "total wind speed"), EPU == "MAB") %>% #filter
  mutate(Time = year(Time)) %>% #find year
  group_by(Time, Var) %>% #group by season
  dplyr::summarise(Value = mean(Value)) %>% #find mean
  
  ggplot()+ #plot
  geom_line(aes(x = Time, y = Value))+
  facet_wrap(.~Var, nrow = 2)+
  ylab("Wind Speed (m/s)") +
  theme_bw()+
  theme(strip.background = element_blank()) 

```


