---
title: "ESP Plot Mock Up"
author: "Kimberly Bastille"
date: "3/22/2021"
output: html_document
---
```{r setup, include=FALSE}

#Default Rmd options
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center') #allows for inserting R code into captions

#Plotting and data libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(ecodata)
library(here)


############################# GIS SETUP ######################################################

#GIS libraries
library(sf)
library(rgdal)
library(raster)
#CRS
crs <- "+proj=longlat +lat_1=35 +lat_2=45 +lat_0=40 +lon_0=-77 +x_0=0 +y_0=0 +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"


#Map line parameters
map.lwd <- 0.4

# Set lat/lon window for maps
xmin = -77
xmax = -65
ymin = 36
ymax = 45
xlims <- c(xmin, xmax)
ylims <- c(ymin, ymax)

#Time series constants
shade.alpha <- 0.3
shade.fill <- "lightgrey"
lwd <- 1
pcex <- 2
trend.alpha <- 0.5
trend.size <- 2
hline.size <- 1
hline.alpha <- 0.35
hline.lty <- "dashed"
label.size <- 5
hjust.label <- 1.5
letter_size <- 4
#feeding.guilds <- c("Apex Predator","Piscivore","Planktivore","Benthivore","Benthos")
x.shade.min <- 2010
x.shade.max <- 2020
#Function for custom ggplot facet labels
label <- function(variable,value){
  return(facet_names[value])
}

```


## Black Sea Bass {.tabset .tabset-fade}


### SST

#### Faceted SST Time series 

```{r}

ESP_seasonal_oisst_anom %>% 
  dplyr::filter(grepl( "sea", ESP)) %>% 
  ggplot2::ggplot()+
  geom_point(aes(x = Time, y = Value))+
  geom_line(aes(x = Time, y = Value))+
  ecodata::geom_gls(aes(x = Time, y = Value))+
  facet_grid(ESP~Var)
```


#### Spring Stock Area
```{r bsb-spring, fig.cap="Seasonal sea surface temperature time series overlaid onto 2020 seasonal spatial anomalies for black seabass spring stock area."}
annotation_custom2 <- function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn,
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}

#EPU shapefile
poly <- ecodata::ESP_sf %>% 
  dplyr::filter(ID %in% c("black_sea_bass_spring")) 

#Map line parameters
map.lwd <- 0.4

# Set lat/lon window for maps
xmin = -81
xmax = -66
ymin = 35.5
ymax = 43
xlims <- c(xmin, xmax)
ylims <- c(ymin, ymax)
sst <- ecodata::seasonal_sst_anomaly_gridded 

sst$Season <- factor(sst$Season, levels = c("Winter",
                                            "Spring",
                                            "Summer",
                                            "Fall"))
sst<- sst %>% dplyr::mutate(Value = replace(Value, Value > 4, 4))
sst_map <- 
  ggplot2::ggplot() +
  ggplot2::geom_tile(data = sst, aes(x = Longitude, y = Latitude,fill = Value)) +
  ggplot2::geom_sf(data = ecodata::coast, size = map.lwd) +
  ggplot2::geom_sf(data = poly, fill = "transparent", size = map.lwd) +
  ggplot2::scale_fill_gradient2(name = "Temp.\nAnomaly (C)",
                       low = scales::muted("blue"),
                       mid = "white",
                       high = scales::muted("red"),
                       limits = c(-4,4),
                       labels = c("<-4", "-2", "0", "2", ">4")) +
  ggplot2::coord_sf(crs = crs, xlim = xlims, ylim = ylims) +
  ggplot2::facet_wrap(Season~.) +
  ecodata::theme_map() +
  ggplot2::ggtitle("SST anomaly (2020)") +
  ggplot2::xlab("Longitude") +
  ggplot2::ylab("Latitude") +
  ggplot2::theme(panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        legend.key = element_blank(),
        axis.title = element_text(size = 11),
        strip.background = element_blank(),
        strip.text=element_text(hjust=0),
        axis.text = element_text(size = 8), 
        axis.title.y = element_text(angle = 90))+
  ecodata::theme_title()

winter_anom <-  ggplot2::ggplotGrob( ecodata::ESP_seasonal_oisst_anom %>% 
                              dplyr::filter(ESP == "black_sea_bass_spring",
                                     stringr::str_detect(Var, "winter")) %>% 
                              dplyr::mutate(hline = mean(Value)) %>% 
                              ggplot2::ggplot(aes(x = Time, y = Value)) +
                              ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
                                       xmin = x.shade.min , xmax = x.shade.max,
                                       ymin = -Inf, ymax = Inf) +
                              ggplot2::geom_line() +
                              ggplot2::geom_point() +
                              ecodata::geom_gls(alpha = trend.alpha + 0.25) +
                              ggplot2::ylab("SST anomaly (C)")+
                              ggplot2::xlab(element_blank())+
                              ggplot2::scale_x_continuous(expand = c(0.01, 0.01)) +
                              ggplot2::geom_hline(aes(yintercept = hline)) +
                              ecodata::theme_ts()+
                              ggplot2::theme(axis.title = element_text(size = 6),
                                    axis.text = element_text(size = 6),
                                    panel.background = element_rect(fill = "transparent"), 
                                    plot.background = element_rect(fill = "transparent", color = NA), 
                                    panel.grid.major = element_blank(),
                                    panel.grid.minor = element_blank(), 
                                    legend.background = element_rect(fill = "transparent"), 
                                    legend.box.background = element_rect(fill = "transparent"), 
                                    legend.key = element_rect(fill = "transparent", colour = NA), 
                                    axis.line = element_blank(),
                                    panel.border = element_blank())
)

spring_anom <-  ggplot2::ggplotGrob( ecodata::ESP_seasonal_oisst_anom %>% 
                              dplyr::filter(ESP == "black_sea_bass_spring",
                                     stringr::str_detect(Var, "spring")) %>% 
                              dplyr::mutate(hline = mean(Value)) %>% 
                              ggplot2::ggplot(aes(x = Time, y = Value)) +
                              ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
                                       xmin = x.shade.min , xmax = x.shade.max,
                                       ymin = -Inf, ymax = Inf) +
                              ggplot2::geom_line() +
                              ggplot2::geom_point() +
                              ecodata::geom_gls(alpha = trend.alpha + 0.25) +
                              ggplot2::ylab("SST anomaly (C)")+
                              ggplot2::xlab(element_blank())+
                              ggplot2::scale_x_continuous(expand = c(0.01, 0.01)) +
                              ggplot2::geom_hline(aes(yintercept = hline)) +
                              ecodata::theme_ts()+
                              ggplot2::theme(axis.title = element_text(size = 6),
                                    axis.text = element_text(size = 6),
                                    panel.background = element_rect(fill = "transparent"), 
                                    plot.background = element_rect(fill = "transparent", color = NA),
                                    panel.grid.major = element_blank(),
                                    panel.grid.minor = element_blank(), 
                                    legend.background = element_rect(fill = "transparent"), 
                                    legend.box.background = element_rect(fill = "transparent"), 
                                    legend.key = element_rect(fill = "transparent", colour = NA), 
                                    axis.line = element_blank(),
                                    panel.border = element_blank())
)

summer_anom <-  ggplot2::ggplotGrob( ecodata::ESP_seasonal_oisst_anom %>% 
                              dplyr::filter(ESP == "black_sea_bass_spring",
                                     stringr::str_detect(Var, "summer")) %>% 
                              dplyr::mutate(hline = mean(Value)) %>% 
                              ggplot2::ggplot(aes(x = Time, y = Value)) +
                              ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
                                       xmin = x.shade.min , xmax = x.shade.max,
                                       ymin = -Inf, ymax = Inf) +
                              ggplot2::geom_line() +
                              ggplot2::geom_point() +
                              ecodata::geom_gls(alpha = trend.alpha + 0.25) +
                              ggplot2::ylab("SST anomaly (C)")+
                              ggplot2::xlab(element_blank())+
                              ggplot2::scale_x_continuous(expand = c(0.01, 0.01)) +
                              ggplot2::geom_hline(aes(yintercept = hline)) +
                              ecodata::theme_ts()+
                              ggplot2::theme(axis.title = element_text(size = 6),
                                    axis.text = element_text(size = 6),
                                    panel.background = element_rect(fill = "transparent"),
                                    plot.background = element_rect(fill = "transparent", color = NA),
                                    panel.grid.major = element_blank(), 
                                    panel.grid.minor = element_blank(), 
                                    legend.background = element_rect(fill = "transparent"),
                                    legend.box.background = element_rect(fill = "transparent"), 
                                    legend.key = element_rect(fill = "transparent", colour = NA), 
                                    axis.line = element_blank(),
                                    panel.border = element_blank())
)

fall_anom <-  ggplot2::ggplotGrob( ecodata::ESP_seasonal_oisst_anom %>% 
                              dplyr::filter(ESP == "black_sea_bass_spring",
                                   stringr::str_detect(Var, "fall")) %>% 
                            dplyr::mutate(hline = mean(Value)) %>% 
                            ggplot2::ggplot(aes(x = Time, y = Value)) +
                            ggplot2::geom_line() +
                            ggplot2::geom_point() +
                            ecodata::geom_gls(alpha = trend.alpha + 0.25) +
                            ggplot2::ylab("SST anomaly (C)")+
                            ggplot2::xlab(element_blank())+
                            ggplot2::scale_x_continuous(expand = c(0.01, 0.01)) +
                            ggplot2::geom_hline(aes(yintercept = hline)) +
                            ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
                                     xmin = x.shade.min , xmax = x.shade.max,
                                     ymin = -Inf, ymax = Inf) +
                            ecodata::theme_ts()+
                            ggplot2::theme(axis.title = element_text(size = 6),
                                  axis.text = element_text(size = 6),
                                  panel.background = element_rect(fill = "transparent"), 
                                  plot.background = element_rect(fill = "transparent", color = NA), 
                                  panel.grid.major = element_blank(), 
                                  panel.grid.minor = element_blank(), 
                                  legend.background = element_rect(fill = "transparent"), 
                                  legend.box.background = element_rect(fill = "transparent"),
                                  legend.key = element_rect(fill = "transparent", colour = NA),
                                  axis.line = element_blank(),
                                  panel.border = element_blank())
)

sst_map + 
  annotation_custom2(grob = winter_anom,  xmin=-82, xmax=-73.75,
                     ymin=39, ymax=43.5, data = data.frame(Season = "Winter")) +
  annotation_custom2(grob = spring_anom,  xmin=-82, xmax=-73.75,
                     ymin=39, ymax=43.5, data = data.frame(Season = "Spring")) +
  annotation_custom2(grob = summer_anom,  xmin=-82, xmax=-73.75,
                     ymin=39, ymax=43.5, data = data.frame(Season = "Summer")) +
  annotation_custom2(grob = fall_anom,  xmin=-82, xmax=-73.75,
                     ymin=39, ymax=43.5, data = data.frame(Season = "Fall"))

```



### Chl

#### Faceted chl Time series 

```{r}

ESP_seasonal_chl %>% 
  dplyr::filter(grepl( "black_sea_bass", ESP)) %>% 
  ggplot2::ggplot()+
  geom_point(aes(x = Time, y = Value))+
  geom_line(aes(x = Time, y = Value))+
  ecodata::geom_gls(aes(x = Time, y = Value))+
  facet_grid(ESP~Var)
```








