# Regime Shift plotting test

What indicators should be included??

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center') #allows for inserting R code into captions

#Plotting and data libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(ecodata)

#Time series constants
shade.alpha <- 0.3
shade.fill <- "lightgrey"
lwd <- 1
pcex <- 2
trend.alpha <- 0.5
trend.size <- 2
hline.size <- 1
hline.alpha <- 0.35
hline.lty <- "dashed"
label.size <- 5
hjust.label <- 1.5
letter_size <- 4
feeding.guilds <- c("Apex Predator","Piscivore","Planktivore","Benthivore","Benthos")
x.shade.min <- 2011
x.shade.max <- 2021
series.col <- c("black","indianred")
#Function for custom ggplot facet labels
label <- function(variable,value){
  return(facet_names[value])
}

```



#### Long Term SST

```{r}
lt_sst <- ecodata::long_term_sst %>% 
  dplyr::mutate(hline = mean(Value, na.rm = TRUE))

hline <- mean(lt_sst$Value)

ecodata::long_term_sst %>% 
  ggplot2::ggplot(aes(x = Time, y = Value, group = Var)) +
  #ecodata::geom_gls() +
  ecodata::geom_regime()+
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::geom_hline(aes(yintercept = hline),
             size = hline.size,
             alpha = hline.alpha,
           linetype = hline.lty)+
  ggplot2::ylab("Temperature (C)") +
  ggplot2::xlab(element_blank())+
  ggplot2::ggtitle("Long-term SST") +
  ggplot2::scale_x_continuous(expand = c(0.01, 0.01), breaks = seq(1840,2010,10))+
  ecodata::theme_facet() +
  ggplot2::theme(strip.text=element_text(hjust=0,
                                face = "italic"))+
  ecodata::theme_title()

```

#### GSI

```{r}
ecodata::gsi %>%
  dplyr::mutate(Year = floor(Time)) %>%
  dplyr::group_by(Year) %>%
  dplyr::summarise(Value = mean(Value)) %>%
  dplyr::mutate(hline = mean(Value)) %>%
  dplyr::rename(Time = Year) %>%
  ggplot2::ggplot(aes(x = Time, y = Value)) +
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls() +
  ecodata::geom_lm(aes(x = Time, y = Value))+
  ecodata::geom_regime()+
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Gulf Stream position anomaly") +
  ggplot2::xlab(element_blank())+
  ggplot2::ggtitle("Gulf Stream Index") +
  ggplot2::scale_x_continuous(expand = c(0.01, 0.01))+
  ggplot2::geom_hline(aes(yintercept = hline),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty)+
  ecodata::theme_ts() +
  ggplot2::theme(strip.text=element_text(hjust=0,
                                face = "italic"))
```

#### Bottom Temp Heatwaves

```{r}
cumu <- ecodata::bottom_heatwave %>% 
  dplyr::filter(Var == "cumulative intensity") %>% 
  dplyr::mutate(Var = dplyr::recode(Var, "cumulative intensity" = "Cumulative Intensity (degree C x days)"))

maxin <- ecodata::bottom_heatwave %>% 
  dplyr::filter(Var == "maximum intensity") %>% 
  dplyr::group_by(Time, EPU, Var, Units) %>% 
  dplyr::summarise(Value = max(Value)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(Var = dplyr::recode(Var, "maximum intensity" = "Maximum Intensity (degree C)"))

hw<- cumu %>%
  rbind(maxin) %>% 
  dplyr::group_by(Var, EPU) %>% 
  dplyr::mutate(hline = mean(Value))

mab.hw<- hw %>% dplyr::filter(EPU == "MAB")
mab.hw %>% 
  ggplot2::ggplot(aes(x = Time, y = Value, group = Var)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ecodata::geom_gls() +
  ecodata::geom_regime()+
  ggplot2::ylab("") +
  ggplot2::xlab(element_blank())+
  ggplot2::ggtitle("Mid-Atlantic Marine Bottom Temp Heatwave Intesity") +
  ggplot2::scale_x_continuous(expand = c(0.01, 0.01))+
  ggplot2::geom_hline(aes(yintercept = hline),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty)+
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ggplot2::facet_wrap(~Var, scales = "free")+
  ecodata::theme_ts()+
  ggplot2::theme(strip.text=element_text(hjust=0,
                                face = "italic"))+
  ecodata::theme_title()
```

#### Warm Core Rings

```{r}
upper.line<-ecodata::wcr %>%
  dplyr::filter(Time>2000) %>% 
  dplyr::mutate(hline = c(mean(Value)))
lower.line<-ecodata::wcr%>%
  dplyr::filter(Time<2000) %>% 
  dplyr::mutate(hline = c(mean(Value)))
wcr<- upper.line %>% 
  rbind(lower.line)

wcr %>% 
  ggplot2::ggplot(aes(x = Time, y = Value))+
    ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ggplot2::geom_point()+
  ggplot2::geom_line()+
  ecodata::geom_regime()+
  ggplot2::ylab("Warm Core Ring Births")+
  ggplot2::xlab(element_blank())+
  ggplot2::ggtitle("Warm Core Rings")+
  ecodata::theme_ts()+
  ggplot2::geom_segment(data = upper.line, aes(x = min(Time), y = hline, 
                                      xend = max(Time), yend = hline, color = "segment") )+
  ggplot2::geom_segment(data = lower.line, aes(x = min(Time), y = hline, 
                                    xend = max(Time), yend = hline, color = "segment") )+
  ggplot2::theme(legend.position = "none")+
  ecodata::theme_title()

```




#### Zooplankton Diversity

```{r}
zoo_div <- ecodata::zoo_diversity %>% 
  dplyr::filter(EPU == "MAB")

zoo_div %>% 
  ggplot2::ggplot(aes(x = Time, y = Value, group = Var)) +
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls() +
  ecodata::geom_lm(aes(x = Time, y = Value, group = Var))+
  ecodata::geom_regime()+
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::ylab("Shannon Diversity") +
  ggplot2::xlab(element_blank())+
  ggplot2::ggtitle("Zooplankton Diversity") +
  ggplot2::facet_wrap(Var~., ncol = 3) +
  ggplot2::scale_x_continuous(expand = c(0.01, 0.01))+
  ggplot2::geom_hline(aes(yintercept = mean(Value)),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty)+
  ecodata::theme_facet() +
  ggplot2::theme(strip.text=element_blank())+
  ecodata::theme_title()
```


#### Expected N

```{r}
exp<- ecodata::exp_n %>% 
  tidyr::separate(Var, into = c("Var", "Season"), sep = "-") %>% 
  dplyr::filter(EPU == "MAB", 
          Season == "FALL", 
          stringr::str_detect(Var, 'AlbatrossSD|BigelowSD')) %>%
  dplyr::rename(VarSD = Var, 
                ValueSD = Value) 
exp2<- ecodata::exp_n  %>% 
  tidyr::separate(Var, into = c("Var", "Season"), sep = "-") %>% 
  filter(EPU == "MAB", 
         Season == "FALL", 
         Var %in% c("Albatross", "Bigelow"))   %>% 

  dplyr::left_join(exp) %>% 
  dplyr::mutate(upper = Value+ValueSD, 
         lower = Value - ValueSD)

exp2 %>% 
ggplot2::ggplot(aes(x = Time, y = Value, fill = Var)) +
  ecodata::geom_regime(data = exp2, aes(x = Time, y = Value, fill = NULL))+
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max ,
      ymin = -Inf, ymax = Inf) +
  ggplot2::geom_ribbon(data = exp2, aes(ymax = pmax(upper, 0), ymin = lower, x = Time),
              alpha = 0.5) +
  ggplot2::geom_line(size = lwd-0.5) +
  ggplot2::geom_point(size = pcex-0.5) +
  
  
  # scale_color_manual(values = series.col, aesthetics = "color")+
  #ggplot2::guides(color = FALSE) +
  #ggplot2::geom_hline(aes(yintercept = hline,
  #               group = Var),
  #           size = hline.size,
  #           alpha = hline.alpha,
  #           linetype = hline.lty)+
  #ggplot2::facet_wrap(Var~.,scales = "free_y", ncol = 2) +
  ggplot2::ggtitle("Expected Number of Species - Fall")+
  
  #ecodata::geom_gls() +
  #Axis and theme
  ggplot2::scale_x_continuous(breaks = seq(1965, 2015, by = 10), expand = c(0.01, 0.01)) +
  ggplot2::ylab("n species per 1000 ind") +
  ggplot2::xlab(element_blank())+
  ecodata::theme_facet()+
  ggplot2::theme(legend.title = element_blank())+
  ggplot2::theme(strip.text=element_text(hjust=0))+
  ecodata::theme_title()

```

#### Productivity
```{r}
#### Adjust plot properties -------------------------------
adjustAxes <- 
  ggplot2::theme(axis.title   = element_text(size = 10),
                 axis.text    = element_text(size = 10),
                 plot.title   = element_text(size = 15))


#### Plot stacked bar with cpts for single var ------------
plot_stackbarcpts_single <- function(YEAR, var2bar,
                                     x, xlab, ylab,
                                     titl,
                                     file_suffix,
                                     leg_font_size = 6,
                                     remove_leg = FALSE,
                                     leg_ncol = 1,
                                     wcpts = TRUE,
                                     wdashed = TRUE,
                                     height = 5.5,
                                     width = 8,
                                     filt = TRUE,
                                     label = label,
                                     y.text = y.text,
                                     aggregate = FALSE) {
  
  dat2bar <- data.frame(YEAR, var2bar,
                        x)
  if (filt == TRUE){mab_species <-  list("SUMMER FLOUNDER","SCUP","BLACK SEA BASS","BLUEFISH",
                                         "NORTHERN SHORTFIN SQUID", "LONGFIN SQUID", "ATLANTIC MACKEREL",
                                         "BUTTERFISH","ATLANTIC SURFCLAM", "OCEAN QUAHOG", "TILEFISH",
                                         "BLUELINE TILEFISH","SPINY DOGFISH", "GOOSEFISH")
  dat2plot <-
    dat2bar %>%
    tidyr::gather(variable, value, -YEAR, -var2bar) %>%
    dplyr::mutate(var2bar = gsub(pattern      = "_", 
                                 replacement  = " ", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl.", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "NS and combined", 
                                 replacement  = "", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "YT", 
                                 replacement  = "Yellowtail", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " GoM", 
                                 replacement  = " GOM", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " by EPU", 
                                 replacement  = "", 
                                 x            = var2bar)) %>%
    dplyr::filter(var2bar %in% mab_species)
} else if (filt == FALSE){
    dat2plot <-
    dat2bar %>%
    tidyr::gather(variable, value, -YEAR, -var2bar) %>%
    dplyr::mutate(var2bar = gsub(pattern      = "_", 
                                 replacement  = " ", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl.", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "NS and combined", 
                                 replacement  = "", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "YT", 
                                 replacement  = "Yellowtail", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " GoM", 
                                 replacement  = " GOM", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " by EPU", 
                                 replacement  = "", 
                                 x            = var2bar))
}
  if (aggregate){
   agg <- dat2plot %>%
     dplyr::group_by(YEAR) %>%
     dplyr::summarise(Total = sum(value, na.rm = T)) %>% 
     dplyr::mutate(Total = ifelse(Total == 0, NA, Total))
  }
  
  p <-   
    ggplot2::ggplot(dat2plot,
           aes(x = YEAR)) +
    ggplot2::geom_bar(data = dat2plot %>% filter(value > 0),
             aes(y = value, fill = var2bar),
             stat = "identity") +
    ggplot2::geom_bar(data = dat2plot %>% filter(value < 0),
             aes(y = value, fill = var2bar),
             stat = "identity") +
    {if(aggregate) geom_line(data = agg,aes(x = YEAR, y = Total),
                             size = 1)} +
    {if(aggregate) ecodata::geom_regime(data = agg, aes(x = YEAR, y = Total))} +
    ggplot2::geom_hline(size = 0.3, aes(yintercept = 0)) +
    ggplot2::xlab(xlab) +
    ggplot2::ylab(ylab) +
    ggplot2::ggtitle(titl) +
    ggplot2::guides(fill = guide_legend(ncol = leg_ncol)) +
    ecodata::theme_ts()+
    ggplot2::theme(axis.title   = element_text(size = 12),
          axis.text    = element_text(size = 12),
          plot.title   = element_text(size = 15),
          legend.text  = element_text(size = leg_font_size),
          legend.title = element_blank()) +
    ggplot2::annotate("text", label = label, x = 1980, y = y.text,size = 8, colour = "black")
  

  
  if(remove_leg) p <- p + theme(legend.position = "none")
  
  return(p)
}

bar_dat <- ecodata::productivity_anomaly %>% 
  dplyr::filter(EPU == "MAB")

# mafmc <-plot_stackbarcpts_single(YEAR = bar_dat$Time,
#                          var2bar = bar_dat$Var,
#                          x = bar_dat$Value,
#                          titl = "",
#                          xlab = "",
#                          ylab = "Small fish per large fish biomass (anomaly)",
#                          height = 5.5,
#                          width = 9,
#                          filt = TRUE,
#                          label = "A",
#                          y.text = 4.5)

# 
mid <- plot_stackbarcpts_single(YEAR = bar_dat$Time,
                         var2bar = bar_dat$Var,
                         x = bar_dat$Value,
                         titl = "",
                         xlab = "",
                         ylab = "Small fish per large fish biomass (anomaly)",
                         height = 5.5,
                         width = 9,
                         filt = FALSE,
                         label = "",
                         y.text = 5,
                         aggregate = TRUE)

mid
```


#### Commercial Landings

```{r}
#Managed landings
managed_landings <- ecodata::comdat  %>%
  dplyr::filter(stringr::str_detect(Var, paste("MAFMC"," managed species - Landings weight|JOINT managed species - Landings weight")),
         !stringr::str_detect(Var, "Other"),
         Time >= 1986,
         EPU == "MAB")

#Total landings
total_landings <- ecodata::comdat  %>%
  dplyr::filter(!stringr::str_detect(Var, "managed species"),
         !stringr::str_detect(Var, "Other"),
         stringr::str_detect(Var, "Landings"),
         Time >= 1986,
         EPU == "MAB")

#Assign feeding guild column for plotting with ggplot
landings <-
  rbind(managed_landings, total_landings) %>%
  dplyr::filter(Var != "Apex Predator Landings") %>%
  dplyr::mutate(feeding.guild = stringr::str_extract(Var,paste(feeding.guilds, collapse = "|")),
         grouping = factor(ifelse(stringr::str_detect(Var,"MAFMC"), "managed",
                                  ifelse(stringr::str_detect(Var, "JOINT"), "joint","total"))),
         Var = paste(stringr::word(feeding.guild), grouping)) %>%
  dplyr::mutate(feeding.guild = factor(feeding.guild, levels = feeding.guilds))

#Add JOINT landings to MANAGED landings and remove
landings[landings$Var ==  "Piscivore managed",]$Value <- landings[landings$Var ==  "Piscivore managed",]$Value + landings[landings$Var ==  "Piscivore joint",]$Value

landings <- landings %>%
  dplyr::filter(Var != "Piscivore joint")  %>%
  dplyr::group_by(Var) %>%
  dplyr::mutate(hline = mean(Value))


#facet names for titles
facet_names <- list("Apex" = expression("Apex"),
                    "Piscivores" = expression("Piscivores"),
                    "Planktivores" = expression("Planktivores"),
                    "Benthivores" = expression("Benthivores"),
                    "Benthos" = expression("Benthos"))

p2<- landings %>%
  dplyr::filter(EPU == "MAB") %>%
  ggplot2::ggplot(aes(x = Time, y = Value, color = grouping)) +

  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +

  #Test for trend and add lines
  ecodata::geom_gls(aes(x = Time, y = Value,
               group = Var)) +
  ecodata::geom_regime()+
  #Add time series
  ggplot2::geom_line(size = lwd) +
  ggplot2::geom_point(size = pcex) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  ggplot2::geom_hline(aes(yintercept = hline,
                 color = grouping,
                 size = grouping),
             size = hline.size,
             alpha = hline.alpha,
             linetype = hline.lty)+

  #Facet
  ggplot2::facet_wrap(feeding.guild~., scales = "free", labeller = label, ncol = 1)+

  #Axis and theme
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2020, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::ylab(expression("Landings (10"^3*"metric tons)")) +
  ggplot2::xlab(element_blank())+
  ecodata::theme_facet() +
  ggplot2::theme(strip.text=element_text(hjust=0))

p2
```
